name: tableflip
main: com.github.kory33.tableflip.TableFlip
version: 0.0.2

commands:
    tableflip:
        description: chat TableFlip emo
        usage: /tableflip text
    unflip:
        description: chat Unflip emo
        usage: /unflip text

